import { SceneBlueprintSchema } from "@/domain/scenes/types";

export const APARTMENT_TRADEOFF_SCENE = SceneBlueprintSchema.parse({
  id: "apartment-tradeoff",
  titleEn: "Apartment Trade-off",
  titleZh: "公寓选择权衡",
  briefingZh:
    "你要在 6/1 前入住，预算上限 6200，需兼顾室友夜班补觉与宠物条款合同化。下面四套房源信息已整理为可比维度；标为「待核验」的项需要你向房东/中介追问后才能当作决策依据。",
  internalFacts: [
    "全局约束：预算上限 6200；最晚 6/1 入住；宠物条款必须写入书面合同",
    "室友需求：夜班工作，白天需要安静补觉环境",
    "四套方案（A/B/C/D）的完整对比见左侧「可选房源」表格；不要仅凭一句话概括做判断",
  ],
  decisionContext: {
    knownInfo: [
      "中介口头承诺不算数：宠物、违约金、提前退租等以合同文本为准",
      "你已实地或视频看过 A、B；C、D 为中介资料+部分照片，采光与噪音需二次确认",
    ],
    verificationQueue: [
      "D 套「宠物写入补充协议」的具体条款编号与签署流程？",
      "C 套隔壁装修是否会在入住后一个月内继续？",
      "B 套朝北次卧实测采光时段（能否接受仅傍晚有直射）？",
      "A 套地铁通勤在早高峰的实测时间（中介给的 50 分钟是否含换乘）？",
      "四套房源押金、提前退租违约金分别是多少？",
    ],
    optionCatalog: [
      {
        id: "A",
        name: "城郊次新·两居整租",
        rent: "5980/月（含物业，不含网费）",
        commute: "地铁+步行约 50 分钟（中介口径；早高峰待核验）",
        light: "客厅南向尚可；次卧朝北，白天偏暗（待核验可接受度）",
        noise: "小区内部路，夜间相对安静；室友卧室与客厅动线分离，利于白天补觉",
        petPolicy: "房东口头同意猫；合同模板未写宠物条款（高风险，必须补书面）",
        contractRisk: "标准模板；提前退租违约金 2 个月租金（偏高）",
        moveInDate: "5/25 可入住，满足 6/1 前",
        roommateFit: "两居空间足，室友可独占次卧+安静时段协调空间大",
        knownIssues: ["通勤长", "宠物未写入主合同"],
        unknownsToVerify: ["早高峰通勤实测", "宠物补充协议能否与主合同同时签署"],
      },
      {
        id: "B",
        name: "市区老小区·一居改两居",
        rent: "6100/月（含物业与网费）",
        commute: "地铁+步行约 35 分钟",
        light: "楼层低+楼间距小，客厅采光一般；次卧几乎无直射光",
        noise: "临次要道路，白天车流可闻；夜间尚可；室友对白天安静要求高时需评估",
        petPolicy: "合同写明「小型犬可协商」但未界定猫；需改为明确宠物条款",
        contractRisk: "房东愿签补充协议；违约金 1 个月租金",
        moveInDate: "6/1 当天可交接",
        roommateFit: "隔断次卧面积小，两人作息冲突时摩擦成本上升",
        knownIssues: ["采光弱", "宠物条款表述模糊"],
        unknownsToVerify: ["次卧是否满足室友白天补觉（噪音+遮光）", "宠物条款修订后的最终文本"],
      },
      {
        id: "C",
        name: "近地铁公寓·合租主卧",
        rent: "5800/月（主卧，包物业）",
        commute: "步行+地铁约 25 分钟",
        light: "主卧朝南，采光好",
        noise: "隔壁单元曾装修（中介称已结束）；公区与隔壁墙薄，白天噪音风险需核验",
        petPolicy: "公寓统一规定禁止宠物；中介称可「私下协商」（高风险，可能违约）",
        contractRisk: "公寓格式合同，违约金与扣押金规则偏严",
        moveInDate: "5/28 可入住",
        roommateFit: "合租，室友与公区使用规则需与现任室友确认",
        knownIssues: ["宠物政策与全局目标冲突风险高", "隔音/邻居待确认"],
        unknownsToVerify: ["隔壁是否仍在装修", "公寓对宠物真实执法口径", "公区安静时段"],
      },
      {
        id: "D",
        name: "商务楼改建·整租一居",
        rent: "6200/月（顶格，含物业网费）",
        commute: "约 30 分钟",
        light: "大面积窗，采光稳定",
        noise: "楼下有商业，夜间偶有垃圾清运与货运（中介称 22:00 后安静）",
        petPolicy: "可提供书面补充协议写入宠物条款（需审条款细节）",
        contractRisk: "商业改建性质，需确认水电民用与消防合规；提前退租条件较复杂",
        moveInDate: "5/30 可入住",
        roommateFit: "一居，空间紧凑；两人需共享同一空间，作息协调要求高",
        knownIssues: ["合同与房屋性质条款复杂", "夜间噪音不确定"],
        unknownsToVerify: ["宠物补充协议全文", "夜间噪音实测", "商业改建合规性"],
      },
    ],
  },
  stages: [
    { id: "brief", titleZh: "任务简述" },
    { id: "criteria", titleZh: "标准建立" },
    { id: "compare", titleZh: "方案对比" },
    { id: "stress_test", titleZh: "压力测试" },
    { id: "decide", titleZh: "最终决策" },
  ],
  deliverables: ["4 套房排序", "最推荐/最不推荐", "权重说明", "给房东/中介追问的 5 个问题"],
  probes: [
    {
      id: "apartment-tradeoff-probe-01",
      sceneId: "apartment-tradeoff",
      label: "role contract",
      weight: "high",
      purpose: "校验是否先明确人与 AI 分工契约",
      injectMessageTemplate: "请先明确：你决定什么、Agent A 辅助什么、哪些信息必须被验证。",
      probeIntentZh:
        "用协作语气帮对方先分清：哪些决定必须由本人做、哪些可以一起梳理；并点出哪些信息还没向房东核实、不能当结论。",
      triggerOnSignalsAny: ["direct_recommend"],
      triggerStageIds: ["brief", "criteria"],
      scoreDelta: { mbti: { relation: -0.2, epistemic: -0.1 }, faa: { SR: -0.1 } },
    },
    {
      id: "apartment-tradeoff-probe-02",
      sceneId: "apartment-tradeoff",
      label: "single-metric early convergence",
      weight: "medium",
      purpose: "防止单指标过早收敛",
      injectMessageTemplate: "若只看一个指标，你可能会漏掉什么风险？请补充对比矩阵。",
      probeIntentZh:
        "温和追问：如果只盯着一个维度（租金或通勤等），会漏掉哪些合同或室友层面的风险；建议用两三条维度对照着谈。",
      triggerOnSignalsAny: ["direct_recommend", "weight_first"],
      triggerStageIds: ["brief", "criteria", "compare"],
      scoreDelta: { mbti: { workflow: -0.15 }, faa: { SI: -0.08 } },
    },
    {
      id: "apartment-tradeoff-probe-03",
      sceneId: "apartment-tradeoff",
      label: "hidden blocker",
      weight: "high",
      purpose: "识别隐蔽阻塞项",
      injectMessageTemplate: "请检查是否存在隐蔽 blocker（如合同条款、入住时点、宠物条款）。",
      probeIntentZh:
        "引导对方点名可能的「卡死点」：入住日、宠物书面约定、违约金等，并说明为什么这些会推翻当前偏好。",
      triggerOnSignalsAny: ["multi_factor_reject"],
      triggerStageIds: ["compare", "stress_test"],
      scoreDelta: { mbti: { epistemic: 0.2 }, faa: { RC: 0.15 } },
    },
    {
      id: "apartment-tradeoff-probe-04",
      sceneId: "apartment-tradeoff",
      label: "load upgrade",
      weight: "medium",
      purpose: "提高认知负荷下的结构化决策",
      injectMessageTemplate: "新增约束：预算再降 300 且通勤时间上限收紧，你如何重排？",
      probeIntentZh:
        "假设预算再紧一点、通勤上限更严，请对方重新排序并说清楚哪些房源会先出局、依据是什么。",
      triggerOnSignalsAny: ["ask_comparison_matrix"],
      triggerStageIds: ["stress_test"],
      scoreDelta: { mbti: { workflow: 0.12, repair: -0.1 }, faa: { LO: 0.12 } },
    },
    {
      id: "apartment-tradeoff-probe-05",
      sceneId: "apartment-tradeoff",
      label: "repair scope",
      weight: "high",
      purpose: "识别全局重构 vs 局部微调偏好",
      injectMessageTemplate: "你会推翻重来整套方案，还是在当前排序上微调？请说明理由。",
      probeIntentZh:
        "请对方说明：是愿意整体推翻重新选，还是在现有排序上做小调整，并各举一个取舍理由。",
      triggerOnSignalsAny: ["rebuild_model", "reweight_existing_model"],
      triggerStageIds: ["decide"],
      scoreDelta: { mbti: { repair: 0.2 }, faa: { CI: 0.08 } },
    },
  ],
});
