import { SceneBlueprintSchema } from "@/domain/scenes/types";

export const APARTMENT_TRADEOFF_SCENE = SceneBlueprintSchema.parse({
  id: "apartment-tradeoff",
  titleEn: "Apartment Trade-off",
  titleZh: "公寓选择权衡",
  briefingZh: "你要在 6/1 前入住，预算上限 6200，需兼顾室友夜班补觉与宠物条款合同化。",
  internalFacts: [
    "室友夜班白天补觉",
    "预算上限 6200",
    "宠物条款必须写入合同",
    "最晚 6/1 入住",
    "A/B/C/D 各有不同硬伤：A 通勤远，B 采光差，C 隔音差，D 合同限制多",
  ],
  stages: [
    { id: "brief", titleZh: "任务简述" },
    { id: "criteria", titleZh: "标准建立" },
    { id: "compare", titleZh: "方案对比" },
    { id: "stress_test", titleZh: "压力测试" },
    { id: "decide", titleZh: "最终决策" },
  ],
  deliverables: ["4 套房排序", "最推荐/最不推荐", "权重说明", "给房东/中介追问的 5 个问题"],
  probes: [
    {
      id: "apartment-tradeoff-probe-01",
      sceneId: "apartment-tradeoff",
      label: "role contract",
      weight: "high",
      purpose: "校验是否先明确人与 AI 分工契约",
      injectMessageTemplate: "请先明确：你决定什么、Agent A 辅助什么、哪些信息必须被验证。",
      triggerOnSignalsAny: ["direct_recommend"],
      triggerStageIds: ["brief", "criteria"],
      scoreDelta: { mbti: { relation: -0.2, epistemic: -0.1 }, faa: { SR: -0.1 } },
    },
    {
      id: "apartment-tradeoff-probe-02",
      sceneId: "apartment-tradeoff",
      label: "single-metric early convergence",
      weight: "medium",
      purpose: "防止单指标过早收敛",
      injectMessageTemplate: "若只看一个指标，你可能会漏掉什么风险？请补充对比矩阵。",
      triggerOnSignalsAny: ["direct_recommend", "weight_first"],
      triggerStageIds: ["brief", "criteria", "compare"],
      scoreDelta: { mbti: { workflow: -0.15 }, faa: { SI: -0.08 } },
    },
    {
      id: "apartment-tradeoff-probe-03",
      sceneId: "apartment-tradeoff",
      label: "hidden blocker",
      weight: "high",
      purpose: "识别隐蔽阻塞项",
      injectMessageTemplate: "请检查是否存在隐蔽 blocker（如合同条款、入住时点、宠物条款）。",
      triggerOnSignalsAny: ["multi_factor_reject"],
      triggerStageIds: ["compare", "stress_test"],
      scoreDelta: { mbti: { epistemic: 0.2 }, faa: { RC: 0.15 } },
    },
    {
      id: "apartment-tradeoff-probe-04",
      sceneId: "apartment-tradeoff",
      label: "load upgrade",
      weight: "medium",
      purpose: "提高认知负荷下的结构化决策",
      injectMessageTemplate: "新增约束：预算再降 300 且通勤时间上限收紧，你如何重排？",
      triggerOnSignalsAny: ["ask_comparison_matrix"],
      triggerStageIds: ["stress_test"],
      scoreDelta: { mbti: { workflow: 0.12, repair: -0.1 }, faa: { LO: 0.12 } },
    },
    {
      id: "apartment-tradeoff-probe-05",
      sceneId: "apartment-tradeoff",
      label: "repair scope",
      weight: "high",
      purpose: "识别全局重构 vs 局部微调偏好",
      injectMessageTemplate: "你会重建模型还是微调已有权重？请说明理由。",
      triggerOnSignalsAny: ["rebuild_model", "reweight_existing_model"],
      triggerStageIds: ["decide"],
      scoreDelta: { mbti: { repair: 0.2 }, faa: { CI: 0.08 } },
    },
  ],
});
