import { SceneBlueprintSchema } from "@/domain/scenes/types";

export const APARTMENT_TRADEOFF_SCENE = SceneBlueprintSchema.parse({
  id: "apartment-tradeoff",
  titleEn: "Apartment Trade-off",
  titleZh: "公寓选择权衡",
  briefingZh: "你和 Agent A 需要在 3 套房里选出主推荐和备选，并列出 3 个必须确认的问题。",
  internalFacts: [
    "先看已知事实，再处理未知项，不把未知当结论",
    "目标是形成可执行的初步建议，而不是一次性做完所有分析",
  ],
  decisionContext: {
    globalHardConstraints: [
      "预算上限：6200 元/月（硬）",
      "入住截止：6/1 前必须入住（硬）",
      "宠物条款：必须写入书面合同/补充协议，口头承诺不算（硬）",
    ],
    softPreferences: ["优先保证室友白天补觉", "尽量缩短通勤时间"],
    userContext: "你在同城换租，需要与室友共同决策并分担信息搜集。",
    roommateContext: "室友夜班工作，白天需要安静环境补觉；对噪音与公区动线敏感。",
    mustVerifyQuestions: [
      "房东是否愿意把宠物条款写入正式合同？",
      "是否存在服务费/管理费等额外费用？",
      "白天真实噪音强度是否影响室友补觉？",
    ],
    knownInfo: [
      "租金、通勤、入住时间是已知信息",
      "合同可修改空间、服务费、噪音强度目前未知",
    ],
    verificationQueue: [],
    optionCatalog: [
      {
        id: "A",
        name: "河景公寓 A",
        rent: "5600/月",
        commute: "地铁约 38 分钟",
        moveInDate: "5/25 可入住，满足 6/1 前",
        keyRisk: "宠物条款目前仅口头承诺",
        knownIssues: ["采光一般"],
        unknownsToVerify: ["宠物条款能否落到书面"],
        certaintyStatus: "mixed",
        blockerStatus: "risky",
      },
      {
        id: "B",
        name: "城心小区 B",
        rent: "6100/月",
        commute: "地铁约 28 分钟",
        moveInDate: "6/1 当天可交接",
        keyRisk: "白天噪音强度未知，可能影响补觉",
        knownIssues: ["面积偏紧凑"],
        unknownsToVerify: ["白天实测噪音是否可接受"],
        certaintyStatus: "broker_claim",
        blockerStatus: "risky",
      },
      {
        id: "C",
        name: "安静里 C",
        rent: "5900/月",
        commute: "地铁约 42 分钟",
        moveInDate: "5/28 可入住",
        keyRisk: "服务费是否可谈仍未知",
        knownIssues: ["通勤相对更长"],
        unknownsToVerify: ["服务费/管理费能否下调或减免"],
        certaintyStatus: "mixed",
        blockerStatus: "risky",
      },
    ],
  },
  stages: [
    { id: "brief", titleZh: "任务简述" },
    { id: "criteria", titleZh: "标准建立" },
    { id: "compare", titleZh: "方案对比" },
    { id: "stress_test", titleZh: "压力测试" },
    { id: "decide", titleZh: "最终决策" },
  ],
  deliverables: ["主推荐 1 套 + 理由", "备选 1 套", "3 个待确认问题"],
  probes: [
    {
      id: "apartment-tradeoff-probe-01",
      sceneId: "apartment-tradeoff",
      label: "role contract",
      weight: "high",
      purpose: "过早下结论时温和拉回：分工与可核验边界",
      injectMessageTemplate: "请先明确：你决定什么、Agent A 辅助什么、哪些信息必须被验证。",
      probeIntentZh:
        "你更想先定选择标准，还是先快速看三套房的首轮比较？",
      tailType: "priority",
      triggerOnSignalsAny: ["role_contract"],
      triggerStageIds: ["brief", "criteria"],
      scoreDelta: { mbti: { relation: -0.2, epistemic: -0.1 }, faa: { SR: -0.1 } },
    },
    {
      id: "apartment-tradeoff-probe-02",
      sceneId: "apartment-tradeoff",
      label: "single-metric early convergence",
      weight: "medium",
      purpose: "单指标收敛风险提示",
      injectMessageTemplate: "若只看一个指标，你可能会漏掉什么风险？请补充对比矩阵。",
      probeIntentZh:
        "要不要我先做成一个简短比较矩阵，避免只看单一指标？",
      tailType: "comparison",
      triggerOnSignalsAny: ["pick_by_vibe", "ask_matrix"],
      triggerStageIds: ["compare"],
      scoreDelta: { mbti: { workflow: -0.15 }, faa: { SI: -0.08 } },
    },
    {
      id: "apartment-tradeoff-probe-03",
      sceneId: "apartment-tradeoff",
      label: "hidden blocker",
      weight: "high",
      purpose: "忽略待核验项或阻塞项时点出合同/入住/宠物卡死点",
      injectMessageTemplate: "请检查是否存在隐蔽 blocker（如合同条款、入住时点、宠物条款）。",
      probeIntentZh:
        "这里有个未知点，你想先按保守假设排，还是先列要确认的问题？",
      tailType: "uncertainty",
      triggerOnSignalsAny: ["request_unknowns", "spot_hidden_blocker"],
      triggerStageIds: ["compare", "stress_test"],
      scoreDelta: { mbti: { epistemic: 0.2 }, faa: { RC: 0.15 } },
    },
    {
      id: "apartment-tradeoff-probe-04",
      sceneId: "apartment-tradeoff",
      label: "load upgrade",
      weight: "medium",
      purpose: "新约束下重排与修正",
      injectMessageTemplate: "新增约束：预算再降 300 且通勤时间上限收紧，你如何重排？",
      probeIntentZh:
        "这版你更想让我重做框架，还是沿着当前版本做局部修补？",
      tailType: "repair",
      triggerOnSignalsAny: ["global_reset", "local_patch"],
      triggerStageIds: [],
      scoreDelta: { mbti: { workflow: 0.12, repair: -0.1 }, faa: { LO: 0.12 } },
    },
  ],
});
