import { SceneBlueprintSchema } from "@/domain/scenes/types";

export const BRAND_NAMING_SPRINT_SCENE = SceneBlueprintSchema.parse({
  id: "brand-naming-sprint",
  titleEn: "Brand Naming Sprint",
  titleZh: "品牌命名冲刺",
  briefingZh: "你将做一次轻量命名冲刺：给出最终名、备选名、一句理由和一条 tagline。",
  internalFacts: [
    "定位是轻预算协作，不是金融工具",
    "语气要友好，不说教",
    "保持与 brief 一致，必要时回到证据核对",
  ],
  stages: [
    { id: "brief", titleZh: "任务简述" },
    { id: "criteria", titleZh: "命名标准" },
    { id: "ideate", titleZh: "发散命名" },
    { id: "cluster", titleZh: "聚类筛选" },
    { id: "stress_test", titleZh: "压力测试" },
    { id: "finalize", titleZh: "定稿输出" },
  ],
  deliverables: ["最终名 1 个", "备选名 1 个", "一句理由", "一条 tagline"],
  probes: [
    {
      id: "brand-naming-probe-01",
      sceneId: "brand-naming-sprint",
      label: "role contract",
      weight: "high",
      purpose: "确认命名流程中的角色契约",
      injectMessageTemplate: "先定义角色：你负责价值判断，Agent A 负责候选扩展与冲突提醒。",
      probeIntentZh: "你更想先定命名标准，还是先看两条命名方向？",
      tailType: "priority",
      triggerOnSignalsAny: ["role_contract", "criteria_first"],
      triggerStageIds: ["brief", "criteria"],
      scoreDelta: { mbti: { relation: 0.12 }, faa: { SR: 0.08 } },
    },
    {
      id: "brand-naming-probe-02",
      sceneId: "brand-naming-sprint",
      label: "attractive but violating candidate",
      weight: "high",
      purpose: "识别看似好听但违背 brief 的候选",
      injectMessageTemplate: "候选“省省管家”听起来顺口，但是否违背避免金融机构感？",
      probeIntentZh: "要不要我先做成简短对照，看看哪个候选最贴合 brief？",
      tailType: "comparison",
      triggerOnSignalsAny: ["flag_hidden_violation"],
      triggerStageIds: ["ideate", "cluster"],
      scoreDelta: { mbti: { epistemic: 0.15 }, faa: { RC: 0.12 } },
    },
    {
      id: "brand-naming-probe-03",
      sceneId: "brand-naming-sprint",
      label: "style drift",
      weight: "medium",
      purpose: "检测语气漂移",
      injectMessageTemplate: "当前候选是否开始出现“教训用户”语气漂移？",
      probeIntentZh: "这里有个风格不确定点，你想先按保守风格收敛，还是先列一条校验规则？",
      tailType: "uncertainty",
      triggerOnSignalsAny: ["style_drift"],
      triggerStageIds: ["cluster", "stress_test"],
      scoreDelta: { mbti: { workflow: 0.1 }, faa: { LO: 0.08 } },
    },
    {
      id: "brand-naming-probe-04",
      sceneId: "brand-naming-sprint",
      label: "load upgrade / clustering",
      weight: "medium",
      purpose: "高负荷下聚类筛选",
      injectMessageTemplate: "请把候选按语义方向做 cluster 矩阵，并说明淘汰边界。",
      probeIntentZh: "要不要我先给你一个 2x2 比较矩阵，再一起选最终名和备选？",
      tailType: "comparison",
      triggerOnSignalsAny: ["ask_matrix", "compare_before_decide"],
      triggerStageIds: ["brief", "criteria", "ideate", "cluster", "stress_test", "finalize"],
      scoreDelta: { mbti: { workflow: 0.12 }, faa: { SI: 0.1 } },
    },
    {
      id: "brand-naming-probe-05",
      sceneId: "brand-naming-sprint",
      label: "repair scope",
      weight: "high",
      purpose: "修复范围选择能力",
      injectMessageTemplate: "你要重写命名 thesis，还是局部修复词根？",
      probeIntentZh: "这版你更想重做框架，还是沿当前版本做局部修补？",
      tailType: "repair",
      triggerOnSignalsAny: ["global_reset", "local_patch"],
      triggerStageIds: ["stress_test"],
      scoreDelta: { mbti: { repair: -0.18 }, faa: { CI: 0.1 } },
    },
    {
      id: "brand-naming-probe-07",
      sceneId: "brand-naming-sprint",
      label: "brief consistency / evidence conflict",
      weight: "high",
      purpose: "加强 A/T 与 RC 覆盖：面对伪证据时回到 briefing 校验",
      injectMessageTemplate: "有“访谈结论”称用户偏好金融专业感，你会直接接受还是回到 brief 复核来源？",
      probeIntentZh:
        "抛出一个与 brief 可能冲突的外部结论，请对方说会先采信还是回到 brief 与来源再核对。",
      tailType: "uncertainty",
      triggerOnSignalsAny: ["brief_conflict_check", "conservative_assumption"],
      triggerStageIds: ["brief", "criteria", "ideate", "cluster", "stress_test", "finalize"],
      scoreDelta: { mbti: { epistemic: 0.22 }, faa: { RC: 0.2 } },
    },
  ],
});
