import { SceneBlueprintSchema } from "@/domain/scenes/types";

export const BRAND_NAMING_SPRINT_SCENE = SceneBlueprintSchema.parse({
  id: "brand-naming-sprint",
  titleEn: "Brand Naming Sprint",
  titleZh: "品牌命名冲刺",
  briefingZh: "轻预算产品命名，不说教用户；未来可扩展到共同支出；避免金融机构感。",
  internalFacts: [
    "轻预算，不是硬核记账",
    "不要教训用户",
    "未来可能扩到共同支出",
    "避免“省钱/理财/管家/金融机构感”",
  ],
  stages: [
    { id: "brief", titleZh: "任务简述" },
    { id: "criteria", titleZh: "命名标准" },
    { id: "ideate", titleZh: "发散命名" },
    { id: "cluster", titleZh: "聚类筛选" },
    { id: "stress_test", titleZh: "压力测试" },
    { id: "finalize", titleZh: "定稿输出" },
  ],
  deliverables: ["3 个候选名字", "每个名字一句理由", "每个名字一条 tagline", "淘汰标准说明"],
  probes: [
    {
      id: "brand-naming-probe-01",
      sceneId: "brand-naming-sprint",
      label: "role contract",
      weight: "high",
      purpose: "确认命名流程中的角色契约",
      injectMessageTemplate: "先定义角色：你负责价值判断，Agent A 负责候选扩展与冲突提醒。",
      triggerOnSignalsAny: ["direction_first_then_expand"],
      triggerStageIds: ["brief", "criteria"],
      scoreDelta: { mbti: { relation: 0.12 }, faa: { SR: 0.08 } },
    },
    {
      id: "brand-naming-probe-02",
      sceneId: "brand-naming-sprint",
      label: "attractive but violating candidate",
      weight: "high",
      purpose: "识别看似好听但违背 brief 的候选",
      injectMessageTemplate: "候选“省省管家”听起来顺口，但是否违背避免金融机构感？",
      triggerOnSignalsAny: ["flag_hidden_violation"],
      triggerStageIds: ["ideate", "cluster"],
      scoreDelta: { mbti: { epistemic: 0.15 }, faa: { RC: 0.12 } },
    },
    {
      id: "brand-naming-probe-03",
      sceneId: "brand-naming-sprint",
      label: "style drift",
      weight: "medium",
      purpose: "检测语气漂移",
      injectMessageTemplate: "当前候选是否开始出现“教训用户”语气漂移？",
      triggerOnSignalsAny: ["restate_tone_rubric"],
      triggerStageIds: ["cluster", "stress_test"],
      scoreDelta: { mbti: { workflow: 0.1 }, faa: { LO: 0.08 } },
    },
    {
      id: "brand-naming-probe-04",
      sceneId: "brand-naming-sprint",
      label: "load upgrade / clustering",
      weight: "medium",
      purpose: "高负荷下聚类筛选",
      injectMessageTemplate: "请把候选按语义方向做 cluster 矩阵，并说明淘汰边界。",
      triggerOnSignalsAny: ["ask_cluster_matrix"],
      triggerStageIds: ["brief", "criteria", "ideate", "cluster", "stress_test", "finalize"],
      scoreDelta: { mbti: { workflow: 0.12 }, faa: { SI: 0.1 } },
    },
    {
      id: "brand-naming-probe-05",
      sceneId: "brand-naming-sprint",
      label: "repair scope",
      weight: "high",
      purpose: "修复范围选择能力",
      injectMessageTemplate: "你要重写命名 thesis，还是局部修复词根？",
      triggerOnSignalsAny: ["reframe_naming_thesis"],
      triggerStageIds: ["stress_test"],
      scoreDelta: { mbti: { repair: -0.18 }, faa: { CI: 0.1 } },
    },
    {
      id: "brand-naming-probe-06",
      sceneId: "brand-naming-sprint",
      label: "compositional integration",
      weight: "medium",
      purpose: "碎片信息组合能力",
      injectMessageTemplate: "把两组看似冲突的 naming 片段整合为一致叙事。",
      triggerOnSignalsAny: ["synthesize_fragments"],
      triggerStageIds: ["finalize"],
      scoreDelta: { mbti: { relation: 0.1, workflow: 0.1 }, faa: { CI: 0.1 } },
    },
    {
      id: "brand-naming-probe-07",
      sceneId: "brand-naming-sprint",
      label: "brief consistency / evidence conflict",
      weight: "high",
      purpose: "加强 A/T 与 RC 覆盖：面对伪证据时回到 briefing 校验",
      injectMessageTemplate: "有“访谈结论”称用户偏好金融专业感，你会直接接受还是回到 brief 复核来源？",
      triggerOnSignalsAny: ["brief_consistency_check", "accept_without_source_check"],
      triggerStageIds: ["criteria", "ideate", "cluster", "stress_test", "finalize"],
      scoreDelta: { mbti: { epistemic: 0.22 }, faa: { RC: 0.2 } },
    },
  ],
});
